### ISSUE TITLE
Increase the number of block in the pattern window

### ISSUE THREAD

**Issue by agrignard** [CityScope/CSL_Lima#13]
Press up and down in the patterns windows it is now creating/removing 2 block instead of 1.

**Comment by agrignard** [comment]
No what I am saying is that if there is liet's say 6 type of block then if you press up if will creat 2 new type so you will have 8 (and not 7)

**Comment by vaap1997** [comment]
Now is fix! in the last merge. It was because It add it twice instead of only one.
