### ISSUE TITLE
Lego reader stange behavior

### ISSUE THREAD

**Issue by agrignard** [CityScope/CSL_Lima#17]
I am a bit surprise that sometime even if the 4 color seems to be well recognized is doesn't give the right id

In this picture it shoudl 6 always but there is one that return -1 whereas it's a 6 
<img width="482" alt="screen shot 2018-07-06 at 14 13 12" src="https://user-images.githubusercontent.com/3928502/42394089-e28c4a28-8126-11e8-8d32-4a43fe73b8b7.png">

If are interested to debug it maybe using the iamge of the cam this is the matrix it came from

<img width="471" alt="screen shot 2018-07-06 at 14 21 34" src="https://user-images.githubusercontent.com/3928502/42394384-f1ddcfd2-8127-11e8-94e7-88d97b2c3969.png">

with this settings
<img width="451" alt="screen shot 2018-07-06 at 14 22 03" src="https://user-images.githubusercontent.com/3928502/42394396-fda93662-8127-11e8-85bf-e075c4cb4e1a.png">

**Comment by vaap1997** [comment]
![captura de pantalla 2018-07-09 a la s 16 07 13](https://user-images.githubusercontent.com/31842957/42477974-b19cf29a-8398-11e8-916f-a0f54621ee19.png)

Hello Arnaud this is now solve in the last merge. Tell me if you have any issues
