### ISSUE TITLE
wiki image not shown

### ISSUE THREAD

**Issue by agrignard** [CityScope/CSL_Lima#22]
@vaap1997 on this page 
https://github.com/CityScope/CSL_Lima/wiki/HumanitarianModel

the image are not displayed 'did you commit them in the wiki?)

**Comment by vaap1997** [comment]
Done!

**Comment by agrignard** [comment]
Good

What about this one also?
https://github.com/CityScope/CSL_Lima/wiki/QRreader

At the end?

**Comment by agrignard** [comment]
@vaap1997 any update on this one?
