### ISSUE TITLE
Legoreader flip in the last commit version

### ISSUE THREAD

**Issue by agrignard** [CityScope/CSL_Lima#25]
I try to update with one of your last version @vaap1997 

however I think you have change lot of stuff and the 2 version are not exactly the same

for instance:

this is what I see with my version running (you can see that what you see on the left screen is the same as in the middle

<img width="1440" alt="screen shot 2018-10-18 at 10 37 36 am" src="https://user-images.githubusercontent.com/3928502/47162652-5e287c00-d2c2-11e8-90ba-8e2b97e47c08.png">

however in the last commit version this is what I have and here you can see it s inverted.

<img width="1440" alt="screen shot 2018-10-18 at 10 39 50 am" src="https://user-images.githubusercontent.com/3928502/47162687-726c7900-d2c2-11e8-8989-cc4fb3ac17da.png">

**Comment by vaap1997** [comment]
Hey! there is a flip attribute. If you press "f" on the keyboard it changes the flipped configuration.

**Comment by agrignard** [comment]
@vaap1997 even with the flip attribute it s not the same behavior

ion the current version what you see on the left is always the mirror of the right (even if you press f)

Would it be possible to have the same on the left and the the right? much more easy to understand for the user

**Comment by vaap1997** [comment]
@jesusGarcia98 did it. I am sick right now... got hepatitis but he fix everything (You meet Jesus in one of our skypes)

**Comment by agrignard** [comment]
Ok thank for the change.

**Comment by agrignard** [comment]
.... I check your l'st commit I don4t know exactly what has been done in the 2 last commits but once agin it s not working...

it deems that the color code are not exactly working, are you also taking care the flip in the "patterns" windows?

It will be important to reach a stable version soon

**Comment by agrignard** [comment]
mmm ok so I think its question of flip 

ok it s seems ok I just had to change the pattern ones, however we have to be careful with that kind of change, imagine if other people were using the same scanner they would also have to change everything.

do you have a table that is testing this script in lima?

**Comment by agrignard** [comment]
Ok I ergot this issue after something like 4-5 hours of running

NullPointerException

**Comment by agrignard** [comment]
see issue #27
