### ISSUE TITLE
Calibration parameters wrong load or save

### ISSUE THREAD

**Issue by agrignard** [CityScope/CSL_Lima#31]
@JesusGarcia98 
In the dev branche if i define a grid which is 12x12 then save it (by pressing S') when i reload it the grid is only 6x6

**Comment by JesusGarcia98** [comment]
For some reason, the amount of blocks was halved when loading the parameters. This is fixed now.

**Comment by agrignard** [comment]
Good job
For the record here is the commit that fixes this issue
https://github.com/CityScope/CSL_Lima/commit/5443a66e88065c15f5c50322a630810d2478aa74
