### ISSUE TITLE
Documentation / Enhancement

### ISSUE THREAD

**Issue by agrignard** [CityScope/CSL_Lima#7]
Patterns:

- With the 6 id
Lets make it even simplier with  (removing the violete)
Red, Green , Blue, Yellow, White, Black 

- Differentiate the color_id and the block_id

- Why not thinking on having more than 6 ids.

Store the grid data in a json file 
This json file could look like this:
https://cityio.media.mit.edu/api/table/citymatrix_volpe

Improve a bit the documentation for the calibration

ColorRange
White calibration:

**Comment by RELNO** [comment]
@agrignard I'm not in the loop, but volpe table follows the old cityIO api ver 1, shouldn't we all converge to v.2?

**Comment by agrignard** [comment]
yep of course maybe this is related to this issue ? 

https://github.com/CityScope/CS_CityIO_Backend/issues/41

**Comment by agrignard** [comment]
BTW Do we have any table following the v2?

**Comment by vaap1997** [comment]
@agrignard The two first are solved. Also the grid file is done. I am not sure if the structure is ok. We are missing adding more patterns_ids. We also change the color panel visualization and the functionality of adding new rows to make it multiple of 4. Documentation about patterns panel is already done. We are using a branch named [UP](https://github.com/CityScope/CSL_Lima/tree/UP)

**Comment by agrignard** [comment]
@vaap1997 what do you mean the two first are solved? 

Did you commit it? I can try to have a look however I am not sure I see your commit

**Comment by vaap1997** [comment]
@agrignard  The two first solved are simplify the color range, and differentiate the color_id and the block_id. Remember you told us, you prefer us to not use the fork, we did the commit on a branch named UP so we can push it to the main once it is ok.

**Comment by vaap1997** [comment]
@agrignard I just did a pull request which, in my opinion cover every change we talk about. Let me know when you have time so we can Skype and check everything
