### ISSUE TITLE
Having the possibility to have n Id in the patterns

### ISSUE THREAD

**Issue by agrignard** [CityScope/CSL_Lima#9]
Hi Vanessa,

As discussed last time , in a next step it can be very useful to be able to define more than 6 type of lego (it could be a parameter where the max will depend on the number of color that we can scan).  

Right now we have the 6 id which is already a good starting but you can think about a next version that will allow the user to define more.

<img width="483" alt="screen shot 2018-06-25 at 16 15 50" src="https://user-images.githubusercontent.com/3928502/41873474-10e9376a-7893-11e8-9e4b-40b74f061647.png">

**Comment by vaap1997** [comment]
@agrignard This is already done, if you press the UP and DOWN arrow in the keyboard you can add new parameters. I have done a push so now if you press "s" on the main sketch you can save the new parameters configuration and it uploads on the calibration JSON.

**Comment by agrignard** [comment]
@vaap1997 oh great it's already there i didn't see it!
